# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 赵圈儿的博客
subtitle: ''
description: ''
keywords: '博客'
author: ZhaoXin
language: zh-CN
timezone: Asia/Shanghai

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://zhaoquaner.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: 默认
category_map:
    默认: default

    编程学习: programming
    Java基础: java
    SpringBoot: springboot
    SpringMVC: springmvc
    Spring: spring
    MyBatis: mybatis
    JavaWeb: javaweb
    Redis: redis

    开发: developing
    数据库: database
    算法: algorithm
    计算机基础: basic

    LeetCode: leetcode
    栈: stack
    队列: queue
    数组: array
    树: tree
    链表: linkedlist
    哈希表: hashset
    图: graph

    教程: tutorial
    工具使用: tool
    学校: school
    生活: life
    读书: reading
    随笔: note

tag_map:
    SpringBoot: springboot
    Spring: spring
    MyBatis: mybatis

    Redis: redis
    缓存数据库: cachedb

    算法: algorithms
    算法题: algo_prblem
    SpringMVC: springmvc
    前端: frontend
    后端: backend
    C++: cpp

    Java基础: java
    泛型: generics
    面向对象: object
    输入输出: io
    线程: thread
    集合: collection
    JDBC: jdbc
    类加载: classloader
    反射: reflect

    JavaWeb: javaweb
    Servlet: servlet
    Jquery: jquery
    AJAX: ajax
    JSP: jsp

    Python: python
    Vue: vue
    工具: tools
    教程: tutorials
    读书: reading


# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: false

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: fluid
#language:zh-CN

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: 'git'
  repo: https://github.com/zhaoquaner/zhaoquaner.github.io.git
  branch: master
  token: 



# hexo-neat
# 博文压缩
neat_enable: true
# 压缩html
neat_html:
  enable: true
  exclude:
# 压缩css  
neat_css:
  enable: true
  exclude:
    - '**/*.min.css'
# 压缩js
neat_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '**/*.min.js'
    - '**/jquery.fancybox.pack.js'
    - '**/index.js'
